server:
  port: 8002

spring:
  application:
    name: payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.calfgz.springcloud.entity

eureka:
  client:
    #表示是否将自己注册进EurekaServer
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server1:7001/eureka, http://server2:7002/eureka, http://server3:7003/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true
