server:
  port: 80

spring:
  application:
    name: consumer-order-feign-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    cn.calfgz.springcloud.service.PaymentService: debug
