server:
  port: 80

spring:
  application:
    name: consumer-order-nacos-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user-service: http://payment-nacos-service
