server:
  port: 7003

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: server3 #eureka服务端实例名称
  client:
    #false 表示不向自己注册中心注册自己
    register-with-eureka: false
    #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖该地址
      defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/

