server:
  port: 3344

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:zzyybs/springcloud-config.git  #github上面的git仓库名字
          uri: git@github.com:calfgz/mall-cloud.git
          search-paths:
            - config/application
      label: master  #读取分支
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}

