server:
  port: 80

spring:
  application:
    name: consumer-order-consul-service

  zipkin:
    base-url: http://localhost:9411
  seluth:
    sampler:
      #采样率值介于0 到 1之间，1表示全部采集
      probability: 1

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
